name: cartesi-rollups-node
x-env: &env
  CARTESI_SNAPSHOTS_DIR: "/var/lib/cartesi-rollups-node/snapshots"
  CARTESI_LOG_LEVEL: ${CARTESI_LOG_LEVEL:-info}
  CARTESI_CONTRACTS_INPUT_BOX_ADDRESS: ${CARTESI_CONTRACTS_INPUT_BOX_ADDRESS:-0x1b51e2992A2755Ba4D6F7094032DF91991a0Cfac}
  CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_AUTHORITY_FACTORY_ADDRESS:-0x5E96408CFE423b01dADeD3bc867E6013135990cc}
  CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_APPLICATION_FACTORY_ADDRESS:-0x26E758238CB6eC5aB70ce0dd52aF2d7b82e1972E}
  CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_SELF_HOSTED_APPLICATION_FACTORY_ADDRESS:-0x010D3CbB4223F5bCc7b7B03cEE59f3aAea8eDb8A}
  CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS: ${CARTESI_CONTRACTS_DAVE_APP_FACTORY_ADDRESS:-0xc3aD8Bb91C5583b416640C2A2dFA59cFf17b8367}
  CARTESI_DATABASE_CONNECTION: postgres://postgres:password@database:5432/rollupsdb?sslmode=disable
  CARTESI_EPOCH_LENGTH: ${CARTESI_EPOCH_LENGTH:-7200}
  CARTESI_BLOCKCHAIN_DEFAULT_BLOCK: ${CARTESI_BLOCKCHAIN_DEFAULT_BLOCK:-finalized}
  CARTESI_AUTH_KIND: ${CARTESI_AUTH_KIND:-private_key}
  CARTESI_AUTH_PRIVATE_KEY: ${CARTESI_AUTH_PRIVATE_KEY:-}
  CARTESI_AUTH_MNEMONIC: ${CARTESI_AUTH_MNEMONIC:-}
  CARTESI_BLOCKCHAIN_ID: ${CARTESI_BLOCKCHAIN_ID:-}
  CARTESI_BLOCKCHAIN_WS_ENDPOINT: ${CARTESI_BLOCKCHAIN_WS_ENDPOINT:-}
  CARTESI_BLOCKCHAIN_HTTP_ENDPOINT: ${CARTESI_BLOCKCHAIN_HTTP_ENDPOINT:-}
  CONSENSUS_ADDRESS: ${CONSENSUS_ADDRESS:-}

services:
  database:
    container_name: database
    image: cartesi/rollups-database:0.12.0-alpha.37
    environment:
      POSTGRES_PASSWORD: password
      <<: *env
    networks:
      - default
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres || exit 1
      timeout: 1s
      interval: 10s
      retries: 5
      start_period: 10s
      start_interval: 200ms
    volumes:
      - pgdata:/var/lib/postgresql/data 

  migrate:
    container_name: migrate
    build:
      dockerfile_inline: |
        # syntax=docker.io/docker/dockerfile:1
        FROM cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
        USER root
        RUN mkdir -p /var/lib/cartesi-rollups-node/logs /var/lib/cartesi-rollups-node/snapshots && chown -R cartesi:cartesi /var/lib/cartesi-rollups-node
        USER cartesi
    user: root
    command: cartesi-rollups-cli db init
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
    networks:
      - default
    environment:
      <<: *env

  evm-reader:
    container_name: evm-reader
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-evm-reader 2>&1 | tee /var/lib/cartesi-rollups-node/logs/evm-reader.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10001:10001"
    environment:
      <<: *env

  advancer:
    container_name: advancer
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-advancer 2>&1 | tee /var/lib/cartesi-rollups-node/logs/advancer.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10002:10002"
      - "10012:10012"
    environment:
      <<: *env

  validator:
    container_name: validator
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-validator 2>&1 | tee /var/lib/cartesi-rollups-node/logs/validator.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10003:10003"
    environment:
      <<: *env

  claimer:
    container_name: claimer
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-claimer 2>&1 | tee /var/lib/cartesi-rollups-node/logs/claimer.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10004:10004"
    environment:
      <<: *env

  jsonrpc-api:
    container_name: jsonrpc-api
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-jsonrpc-api 2>&1 | tee /var/lib/cartesi-rollups-node/logs/jsonrpc-api.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10005:10005"
      - "10011:10011"
    environment:
      <<: *env

  prt:
    container_name: jsonrpc-api
    image: cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
    command: ['bash','-c','cartesi-rollups-prt 2>&1 | tee /var/lib/cartesi-rollups-node/logs/prt.log']
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    ports:
      - "10005:10006"
    environment:
      <<: *env

  nginx:
    build:
      dockerfile_inline: |
        # syntax=docker.io/docker/dockerfile:1
        FROM nginx:alpine
        COPY <<EOF /etc/nginx/nginx.conf
        worker_processes  auto;
        error_log  /var/log/nginx/error.log notice;
        pid        /var/run/nginx.pid;
        events {
            worker_connections  1024;
        }
        http {
            include       /etc/nginx/mime.types;
            default_type  application/octet-stream;
            log_format  main  '\$$remote_addr - \$$upstream_cache_status rt=\$$request_time [\$$time_local] "\$$request" '
                              '\$$status \$$body_bytes_sent "\$$http_referer" '
                              '"\$$http_user_agent" "\$$http_x_forwarded_for" '
                              'uct="\$$upstream_connect_time" uht="\$$upstream_header_time" urt="\$$upstream_response_time"';
            access_log  /var/log/nginx/access.log  main;
            sendfile        on;
            keepalive_timeout  65;
            map \$$request_method \$$purge_method {
                PURGE 1;
                default 0;
            }
            proxy_cache_path /var/cache keys_zone=mycache:200m;
            include /etc/nginx/sites-enabled/*;
        }
        EOF
        COPY <<EOF /etc/nginx/sites-enabled/node.conf
        server {
            listen       80;
            listen  [::]:80;
            location /inspect {
                proxy_pass   http://advancer:10012/inspect;
            }
            location /rpc {
                proxy_pass   http://jsonrpc-api:10011/rpc;
            }
            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
        EOF
    command: /usr/sbin/nginx -g "daemon off;"
    ports:
      - "8080:80"

  deployer:
    build:
      dockerfile_inline: |
        # syntax=docker.io/docker/dockerfile:1
        FROM cartesi/rollups-runtime:${CARTESI_RUNTIME_VERSION:-0.12.0-alpha.37}
        USER root
        RUN apt update && apt install -y --no-install-recommends curl ca-certificates jq
        ADD --chmod=755 https://gist.github.com/lynoferraz/15a627bbc16ac61afa44646af8628d04/raw/498d7ccae65c5ef1b7bdee7fb28b5eb843f2f12b/deployer.sh /usr/local/bin/deployer.sh
        USER cartesi
    command: echo "Deployer - nothing to do"
    depends_on:
      database:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
    networks:
      - default
    volumes:
      - cartesi-rollups-node-data:/var/lib/cartesi-rollups-node
    environment:
      <<: *env

volumes:
  cartesi-rollups-node-data:
  pgdata: